export const EMPLOYEE_STATUS = {
  DRAFT: 'DRAFT',
  PROBATION: 'PROBATION',
  ACTIVE: 'ACTIVE',
  NOTICE_PERIOD: 'NOTICE_PERIOD',
  SUSPENDED: 'SUSPENDED',
  INACTIVE: 'INACTIVE',
  RESIGNED: 'RESIGNED',
  TERMINATED: 'TERMINATED',
  EXITED: 'EXITED'
};

export const EMPLOYMENT_TYPE = {
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  CONTRACT: 'CONTRACT',
  INTERN: 'INTERN'
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  DEACTIVATED: 'DEACTIVATED'
};

export const PUNCH_TYPE = {
  IN: 'IN',
  OUT: 'OUT'
};

export const PUNCH_SOURCE = {
  WEB: 'WEB',
  MOBILE: 'MOBILE',
  BIOMETRIC: 'BIOMETRIC',
  QR: 'QR',
  NFC: 'NFC',
  API: 'API'
};

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  HALF_DAY: 'HALF_DAY',
  ON_LEAVE: 'ON_LEAVE',
  HOLIDAY: 'HOLIDAY',
  WEEK_OFF: 'WEEK_OFF'
};

export const REGULARISATION_STATUS = {
  SUBMITTED: 'SUBMITTED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

export const LEAVE_CATEGORY = {
  ANNUAL: 'ANNUAL',
  SICK: 'SICK',
  CASUAL: 'CASUAL',
  MATERNITY: 'MATERNITY',
  PATERNITY: 'PATERNITY',
  BEREAVEMENT: 'BEREAVEMENT',
  UNPAID: 'UNPAID', // LWP
  COMPENSATORY_OFF: 'COMPENSATORY_OFF',
  SABBATICAL: 'SABBATICAL',
  CUSTOM: 'CUSTOM'
};

export const LEAVE_REQUEST_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

export const LEAVE_LEDGER_TRANSACTION_TYPE = {
  ACCRUAL: 'ACCRUAL',
  AVAILED: 'AVAILED',
  ADJUSTMENT: 'ADJUSTMENT',
  LAPSED: 'LAPSED',
  ENCASHED: 'ENCASHED',
  CANCELLATION: 'CANCELLATION'
};

export const AUDIT_ACTION = {
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  EMPLOYEE_DEACTIVATED: 'EMPLOYEE_DEACTIVATED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  PUNCH_CREATED: 'PUNCH_CREATED',
  ATTENDANCE_OVERRIDE: 'ATTENDANCE_OVERRIDE',
  REGULARISATION_SUBMITTED: 'REGULARISATION_SUBMITTED',
  REGULARISATION_APPROVED: 'REGULARISATION_APPROVED',
  REGULARISATION_REJECTED: 'REGULARISATION_REJECTED',
  ATTENDANCE_LOCKED: 'ATTENDANCE_LOCKED',
  LEAVE_POLICY_CREATED: 'LEAVE_POLICY_CREATED',
  LEAVE_POLICY_UPDATED: 'LEAVE_POLICY_UPDATED',
  LEAVE_REQUESTED: 'LEAVE_REQUESTED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  LEAVE_BALANCE_ADJUSTED: 'LEAVE_BALANCE_ADJUSTED',
  LEAVE_DELEGATED: 'LEAVE_DELEGATED',
  LEAVE_DELEGATION_REVOKED: 'LEAVE_DELEGATION_REVOKED',
  LEAVE_BLACKOUT_CREATED: 'LEAVE_BLACKOUT_CREATED',
  LEAVE_BLACKOUT_UPDATED: 'LEAVE_BLACKOUT_UPDATED',
  LEAVE_ENCASHED: 'LEAVE_ENCASHED',
  LEAVE_ACCRUED: 'LEAVE_ACCRUED',
  LEAVE_ESCALATED: 'LEAVE_ESCALATED',
  EMPLOYEE_TRANSFERRED: 'EMPLOYEE_TRANSFERRED'
};
